name: wandxinc_core
description: A Very Good Project created by Very Good CLI.
version: 3.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  chopper: ^8.0.1+1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  pretty_chopper_logger: ^1.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
